[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transparency_anchor = "2ziQobdPPPsgdc7e7Py1mZNs3UrhwiReUJH59ehW67Fd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
